name: Build C++ to EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout kode repositori
      uses: actions/checkout@v4

    - name: Kompilasi C++ ke EXE
      run: |
        g++ -o program.exe project1.cpp

    - name: Simpan file EXE sebagai Artifact
      uses: actions/upload-artifact@v4
      with:
        name: program-exe
        path: program.exe
